# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test All The Versions!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']
        django-version: ['2.2', '3.0', '3.1']
        exclude:
          - python-version: '3.5'
            django-version: '3.0'
          - python-version: '3.5'
            django-version: '3.1'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade Django~=${{ matrix.django-version }}.0 .[dev]
    - name: Test with pytest
      run: py.test
